#!/usr/bin/python3
def raise_exception():
    y = "string"
    x = 11
    z = y + x
